import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Partials/Header'
import Footer from '@/components/Partials/Footer'
import { montserrat } from './fonts'

export const metadata: Metadata = {
    title: 'Grand Boulevard',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
